# Default values for postgres-instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

DBName: "container"
Username: "hmuser"
Size: "100M"
Instances: 2
DBVersion: 10
