KafkaUsername: "kafka-ui-user"
KafkaPassword: "kafka-ui-user"
KafkaCluster: "kafka-kafka-instance"
BootstrapServers: kafka-kafka-instance-kafka-brokers:9092

kafka-ui:
  yamlApplicationConfigConfigMap:
    name: "kafka-ui-configmap"
    keyName: "config.yml"

